---
title: "hippohacks RMarkdown"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
## Introduction

In this hackathon we will be calling many different APi's in order to get information on different transportation stuffs. First goal is to get some of the venders.
```{r}
library(httr)
library(jsonlite)
library(broom)
library(dplyr)
```


```{r}
#define the function
get_Capital <- function(url) {
  doot <- fromJSON(url)
  doot2 <- doot$data
  doot3 <- do.call(what = "rbind",
                           args = lapply(doot2, as.data.frame))
  return(doot3)
}
```

```{r}
# Get capital bikeshare locations and status
station_DataDF <- get_Capital("https://gbfs.capitalbikeshare.com/gbfs/en/station_information.json")
station_statusDF <- get_Capital("https://gbfs.capitalbikeshare.com/gbfs/en/station_status.json")
station_BigData <- station_DataDF %>%
  left_join(station_statusDF, by = "station_id")
```

```{r}
library(DCmapR)
ward_df <- get_Ward(dataframe = TRUE)
ggplot() +
  geom_polygon(data = ward_df, aes(x = long, y = lat, group = group, fill = factor(Ward)),
               col  = "black", alpha = 0.3, size = 1) + 
  scale_fill_discrete(name = "Ward") + 
  geom_point(data = station_BigData, aes(x = lon, y = lat, group = station_id), col = "black") +
  coord_quickmap()
```

```{r}
library(plotly)
Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoibWFzdGVyYmluZ28xIiwiYSI6ImNqdDluOHo2aDAxenQ0OW51dmdkOGIyaDkifQ.KMv1Wkds1VtmtzOOmMWuiw')
plot_mapbox(mode = "scattermapbox", marker = list(symbol = "bicycle", size = 10, col = "blue")) %>%
  add_markers(data = station_BigData, x = ~ lon, y = ~ lat,
              hoverinfo = "text",
            text = ~paste('Name: ', name,
                          '\n Available Bikes: ', num_bikes_available,
                          '\n Available Docks: ', num_docks_available)) %>%
  layout(mapbox = list(zoom = 10.5,
                       center = list(lat = ~median(station_BigData$lat),
                                     lon = ~median(station_BigData$lon)),
                       style = "outdoors"))
```

